### ISSUE TITLE
I just can't sort out why any of these approached/ edits are unresponsive.

### ISSUE THREAD

**Issue by kevinbloomquist** [den-wdi-2/tic-tac-toe#2]
I've visited too many google links to list here but I think the links below will paint the current arc of my relationship to this project. I totally get this and I know I'm missing something simple that I am later going to kick myself for. I'm in good spirits and certainly not beat here but I feel like I've moved beyond anything remotely pedagogical and am now wasting alot of valuable time just staring at a screen and typing anything that could possibly make a change. Any thoughts would be welcome.

https://github.com/kevinbloomquist/tic-tac-toe/commit/71301c056cace6b13f9dae9f875bbe27ca9470dc

https://github.com/kevinbloomquist/tic-tac-toe/commit/fa5c7ad24cfcdd98dd38118a536f71f0ba42d348

https://github.com/kevinbloomquist/tic-tac-toe/commit/26b12423809c3a2988cc5abcbab5316b59783372

https://github.com/kevinbloomquist/tic-tac-toe/commit/7e1e725801095e1a8e90986a4cdee994f4eeffbe

**Comment by ZebGirouard** [comment]
hi @kevinbloomquist , one thing that may be helpful is removing the click listener from the #grid section.  this covers the whole tic-tac-toe board, so i'm pretty sure this is overriding your click listeners on the individual boxes
