### ISSUE TITLE
Why cant i get the message to appear on page...

### ISSUE THREAD

**Issue by GisellaBella** [den-wdi-2/tic-tac-toe#3]
it's driving me nuts and keeping me from moving forward.
https://github.com/GisellaBella/tic-tac-toe/blob/master/js/app.js

**Comment by ZebGirouard** [comment]
Hi Gisella,

@GisellaBella , I'm pretty sure the issue revolves around `onclick` in your HTML.  

http://stackoverflow.com/questions/17378199/uncaught-referenceerror-function-is-not-defined-with-onclick

I would encourage you to use the click listeners we used for Lord of the Rings or our jQuery lessons.

**Comment by nickandersonr** [comment]
Hi Gisella - was Zeb able to answer your question? If so, I'll close this issue.
